# Generated by Django 5.1.4 on 2025-01-05 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('desenvolvedora', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('classificacao', models.CharField(max_length=50)),
                ('data_lancamento', models.DateField()),
                ('comentario', models.TextField()),
                ('nota', models.FloatField()),
                ('capa', models.ImageField(blank=True, null=True, upload_to='capas/')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameinsight.genero')),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameinsight.plataforma')),
            ],
        ),
    ]
