# Generated by Django 5.1.4 on 2025-01-08 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gameinsight', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jogo',
            name='classificacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameinsight.classificacao'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameinsight.genero'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='jogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameinsight.jogo'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='plataforma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameinsight.plataforma'),
        ),
    ]
