# Generated by Django 5.1.3 on 2024-11-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameinsight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='nota',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='Destaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destaque', models.ManyToManyField(to='gameinsight.jogo')),
            ],
        ),
    ]
