# Generated by Django 5.1.3 on 2024-11-24 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameinsight', '0002_alter_jogo_nota_destaque'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Destaque',
        ),
    ]
