# Generated by Django 5.1.4 on 2025-01-08 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameinsight', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='media',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='nota',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
