# Generated by Django 5.1.3 on 2024-11-24 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameinsight', '0003_delete_destaque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogo',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='plataforma',
        ),
        migrations.AddField(
            model_name='jogo',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gameinsight.genero'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='plataforma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gameinsight.plataforma'),
        ),
    ]
