# Generated by Django 5.1.4 on 2025-01-11 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameinsight', '0003_jogo_media_alter_avaliacao_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='jogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='gameinsight.jogo'),
        ),
    ]
