# Generated by Django 5.1.3 on 2024-11-24 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameinsight', '0004_remove_jogo_genero_remove_jogo_plataforma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameinsight.genero'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='plataforma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameinsight.plataforma'),
        ),
    ]
