# Generated by Django 5.1.4 on 2024-12-08 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameinsight', '0006_alter_usuario_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cpf',
        ),
    ]
