# Generated by Django 5.1.4 on 2024-12-08 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameinsight', '0007_remove_usuario_cpf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
